language: java
jdk:
- openjdk8
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS: 1
  - GCLOUD_PROJECT: strapdata-gcp-partnership
  - GCLOUD_ZONE: europe-west1-b
  - IMAGE_SUFFIX=-staging
  - PULL_SECRET=nexus-registry
  - MEMORY_REQUEST=2048Mi
  - MEMORY_LIMIT=2048Mi
  - HELM_URL=https://get.helm.sh
  - HELM_TGZ=helm-v2.14.3-linux-amd64.tar.gz
  - secure: TiNtg/r4v4wUteKlhjxhdcM4NIN9592mI6TOnhfGBZavxnoAIqumYuM69UligT0KmfAnblxxQ6ZTPCjKurccKhI8ALvPkZCxrbv8AAbN1cmzxiyYwUgA3J9z2CAUsI+2IR4vW8LYzi8srflFfb7ud6VcFJgU7amWvz1gNy7OzgNgXzd4M6xgIH2JbntB/Umqaz5Y1UbZ22w9vXayJQxI77mlXY2yhQy8h/wys7MRDIR/cDTh3GauQtGLclURnkAr32rzY1RrZfaGaMFs74jYA3M19r7rq4J3LR2vbnRM3a/fstRFhAzsfgFfxkM5GCaNZqcMESL6HWjW/TiS66Z3YdClIp5KHRZTMb5LO3oTceANiP2eI/ODzKTN/ttHQq+mVpkz6Tw57dpB/hfLk8aTIJvhNdAxlQwFpoVUURxavqRJlT6FxpzR3DHqugyGjM2TWuMMxW1EEF0XGW35fJsfJtF7nIJng2HYBIXtLzNY7W0VmVs+31X/FDq4xdJB++6wUS3pH+AvdlvIkOqpLZ80hP88fvq5HQmxSRmoUzwVT7qdhCbKLDeISwzBk1fCTQnc9AMBpdz7zU3whWu6jHVZ91+7/qxeIqYvVr3Yi86r+0voMQLm3s5/vfsdxUZ7+ldxn2y2V0/OY34k6nLdSOMh+G7pkYp3DvX800e/rwyC6nk=
  - secure: J8pFYjs6Pie1aT3qb40hjptyMup5yoiewCnT7EGCGgRyNwP5cV0CGU+STwnLhLnsN+qfu/8T6ZR+aDskPk5lvvkCksQSrDQR0y3Qr4hoWpS/jZNGC8x4DApt9BSlWlWI/8P5x0RS25jX9whwHmgwdK3BtGA4CkatArepigokvZ7h/ySis5hiU83AxhqVRS4tTk46UOD9KOhgZlb548YMmJmoOnigZL3rzMbfHbt5WeKjIo55tS40jy/E1JWRSRiu8zWJqziwsnkOXeZ6OSzIJp+gYiqvKnImbGZ8pktl7Wn+ORL4VHYhQxxcYb5LqY4kjAG3UFyNn/NbQDFJ1GE3KPiJDszVOc5uog4RZ2KbqTRbZ4N8Hgg1lbC1NM4auh8swn/5+QYpwhpET31mMyYU2yp/fxnmM/BcVTz/g1q5or9zitiG3yRtJZ31b4bCW2AOoApxnb2K/jZOpbE3nmNOl5gUeEp6zkPP8UO4D0AIMkXpanqqtus0ar12ls6bWRMo9Y77SbCehiHlt5TlbGaNar64uQ2XcYQ0Gnpr/eaEC/m/IiJzs/4b6i6IpG2eG1l6ZNeLS1DfRY/eIL4an9/0an4SwzAKurPXagGWjejAyqKrOOreYUcT8KcpNFH+M9nodIlMpa3TEPanO9iVQa78WLBv0jYVarjypCS9IHiFKis=
  - secure: "OXfOanqOrQCU8kytlq/yQvMpSkFi1BG4tOVl33yUeTkAx8HT4MfY/28ClAljDP3m3ekwgUvV9NXFWexSMAVyzJK4zSrSQxy4Qq9oh61OOFdVwAEPUx7hb0WjeUnHDGilNvTgTvx6ySr/BI9/zPsDq26bU4M+RrzVqPrmD6baIGXYq7FoTMuSrNJN3mko934Tz8Q7IyaSk6evO6CC2Sc9Eqlfz+1x8Pna+QKfSNjUYGgOhbPfmcMEuBIvrRWEMigB8Tpqjq8/H6i5+CyvXu/xpOXeiUUCu1h2UesHAcdrtO+hwCrp68fFsef1aaltzTouJwGhcpBTKk0ShrsICQscILksHDjb+Lnw6QevUQgvF1PxIMDK1qM7QuELBc/HQU2C8Kq5lfr6H3rp3j3wc+E7lCajhAZNpazN/lSDveSXfgFB6ZdmWpnt/vETnVJ+8rtHTIZskAn5RZ38TtLKm6gOwFPkLyhKuYmhKz4MRepiSFMqJ5hRQdtPmZM5ZQK6uxjy0ZSd3wWitesC8rBNebCx7LsAtCNqnBujNyvpjMuBrt0dq+R8Gdp1w5Yg6l5Jwzpy+7xnAFaMCwRQAK52KrxR8MUS2mXHwcQYkPDz0TFBuId0u6Fn9KkZ5nkxX3D/KRL1clcPxnJYb4RgW/8egfOZFaxVqh9LI5NffmvT52cmPrM=" # AZ_USERNAME
  - secure: "Ynxz4MG82aWwezKY4w5Np7mUMT8E2K+4qq2fh2fEO4EpWXXHPy2go9pzFXP333Z1ILSy1G2uMXuhkeQ9aBNGx0r3uHuD+r5OwrAWomaGrnQ1nQOb1VEJS58Y5QIAvSZIyVguIObQSE1KAI8BEislBBRzjfA/4g1Ar/vOxzn08Ja9ZAPoD3LiYE2vPA/8jpL/qj4iexslXTTp70l8J4DyHcptXymfjLPy6ahkT0RC6nTjCLspuYRHt8gc4qYQDboQh0h8uymxwnvcl1TD6Lv8DWRokwyfgX2FNSkphLGmdGoKDeYAL7az4B+OrnguFZgxlKuUbrOq9RLdFxph/QoOW7M4mBAgtpIw5y+vjfZo8Q3ZAzBPEAFO5yoWuHGvT/nHcGd0qJy0cwMjFNmLk/hkR1w04s/4RrX++YGkCjD39uG7JStXFsJUJBpn4tH3DWvldEPmcNU2VMzAIa4MCX7nz/AIedh3G2PZXMjpqA4NB+9YpRpIfAWOjrVBjtiz+yDGaK4AgdgmB4hqcyQd9wffnf5w/yehDwd7+LRkqR7j0ZmBXG87rmzhr8kuS/5DxmHkuWSudwC8GvQbGtv9EQaKf7tWVeVwPjAfI+mJINnJcbyX6JvxU+tsWwVqEMx5S4kBT8XZ7/Xx8ZIGk92vg4VTR+kPsS3l2+RJV+2nBTTA0uY=" # AZ_PASSWORD
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/google-cloud-sdk/"
services:
- docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin strapdata.azurecr.io
  - echo "$NEXUS_PASSWORD" | docker login -u "$NEXUS_USERNAME" --password-stdin https://docker.repo.strapdata.com
install:
- "./gradlew --version"
# Installing Helm
- wget -q ${HELM_URL}/${HELM_TGZ}
- tar xzfv ${HELM_TGZ}
- PATH=`pwd`/linux-amd64/:$PATH
- helm init --client-only
script:
- "./gradlew build"
deploy:
- provider: script
  skip_cleanup: true
  script:
  - ./gradlew dockerPush -PregistryUsername=$NEXUS_USERNAME -PregistryPassword=$NEXUS_PASSWORD
    -Dorg.gradle.project.dockerImagePrefix="docker.repo.strapdata.com/strapdata/elassandra-"
    -Dorg.gradle.project.dockerImageSuffix="-dev"
    -Dorg.gradle.project.elassandraParentImage="strapdata/elassandra-enterprise"
  - ./gradlew publish -PrepoUsername=$NEXUS_USERNAME -PrepoPassword="$NEXUS_PASSWORD"
  on:
    tags: false
    all_branches: true
#    condition: $TRAVIS_BRANCH =~ ^develop-.*

- provider: script
  skip_cleanup: true
  script:
  - ./gradlew dockerPush -PregistryUsername=$NEXUS_USERNAME -PregistryPassword=$NEXUS_PASSWORD
    -Dorg.gradle.project.dockerImagePrefix="docker.repo.strapdata.com/strapdata/elassandra-"
    -Dorg.gradle.project.dockerImageSuffix=""
    -Dorg.gradle.project.elassandraParentImage="strapdata/elassandra-enterprise"
  - ./gradlew dockerPush -PregistryUsername=$AZ_USERNAME -PregistryPassword=$AZ_PASSWORD
    -Dorg.gradle.project.dockerImagePrefix="strapdata.azurecr.io/strapdata/elassandra-"
    -Dorg.gradle.project.dockerImageSuffix=""
    -Dorg.gradle.project.elassandraParentImage="strapdata/elassandra-enterprise"
  - ./gradlew publish -PrepoUsername=$NEXUS_USERNAME -PrepoPassword="$NEXUS_PASSWORD"
  # push to GCR.IO done by the marketplace repository
  on:
    tags: true
    branch:
      - master
