language: java
jdk:
- openjdk8
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS: 1
  - GCLOUD_PROJECT: strapdata-gcp-partnership
  - GCLOUD_ZONE: europe-west1-b
  - IMAGE_SUFFIX=-staging
  - PULL_SECRET=nexus-registry
  - MEMORY_REQUEST=2048Mi
  - MEMORY_LIMIT=2048Mi
  - HELM_URL=https://get.helm.sh
  - HELM_TGZ=helm-v2.14.3-linux-amd64.tar.gz
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/google-cloud-sdk/"
services:
- docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin strapdata.azurecr.io
  - echo "$NEXUS_PASSWORD" | docker login -u "$NEXUS_USERNAME" --password-stdin https://docker.repo.strapdata.com
install:
- "./gradlew --version"
# Installing Helm
- wget -q ${HELM_URL}/${HELM_TGZ}
- tar xzfv ${HELM_TGZ}
- PATH=`pwd`/linux-amd64/:$PATH
- helm init --client-only
script:
- "./gradlew build"
deploy:
- provider: script
  skip_cleanup: true
  script:
  - ./gradlew dockerPush -PregistryUsername=$DOCKER_USERNAME -PregistryPassword=$DOCKER_PASSWORD -PregistryUrl=strapdata.azurecr.io
    -Dorg.gradle.project.dockerImagePrefix="strapdata.azurecr.io/strapdata/elassandra-"
    -Dorg.gradle.project.dockerImageSuffix=""
    -Dorg.gradle.project.elassandraParentImage="strapdata/elassandra-enterprise"
  - ./gradlew dockerPush -PregistryUsername=$NEXUS_USERNAME -PregistryPassword=$NEXUS_PASSWORD -PregistryUrl="docker.repo.strapdata.com"
      -Dorg.gradle.project.dockerImagePrefix="docker.repo.strapdata.com/strapdata/elassandra-"
      -Dorg.gradle.project.dockerImageSuffix="-dev"
      -Dorg.gradle.project.elassandraParentImage="strapdata/elassandra-enterprise"
  - ./gradlew publish -PrepoUsername=$NEXUS_USERNAME -PrepoPassword="$NEXUS_PASSWORD"
  on:
    tags: false
    all_branches: true
#    condition: $TRAVIS_BRANCH =~ ^develop-.*

- provider: script
  skip_cleanup: true
  script:
  - ./gradlew dockerPush -PregistryUsername=$DOCKER_USERNAME -PregistryPassword=$DOCKER_PASSWORD -PregistryUrl=strapdata.azurecr.io
    -Dorg.gradle.project.dockerImagePrefix="strapdata.azurecr.io/strapdata/elassandra-"
    -Dorg.gradle.project.dockerImageSuffix=""
    -Dorg.gradle.project.elassandraParentImage="strapdata/elassandra-enterprise"
  - ./gradlew dockerPush -PregistryUsername=$NEXUS_USERNAME -PregistryPassword=$NEXUS_PASSWORD -PregistryUrl="docker.repo.strapdata.com"
      -Dorg.gradle.project.dockerImagePrefix="docker.repo.strapdata.com/strapdata/elassandra-"
      -Dorg.gradle.project.dockerImageSuffix=""
      -Dorg.gradle.project.elassandraParentImage="strapdata/elassandra-enterprise"
  - ./gradlew publish -PrepoUsername=$NEXUS_USERNAME -PrepoPassword="$NEXUS_PASSWORD"
  # push to GCR.IO done by the marketplace repository
  on:
    tags: true
    branch:
      - master
