language: java
jdk:
- openjdk8
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS: 1
  - GCLOUD_PROJECT: strapdata-gcp-partnership
  - GCLOUD_ZONE: europe-west1-b
  - IMAGE_SUFFIX=-staging
  - PULL_SECRET=nexus-registry
  - MEMORY_REQUEST=2048Mi
  - MEMORY_LIMIT=2048Mi
  - HELM_URL=https://get.helm.sh
  - HELM_TGZ=helm-v2.14.3-linux-amd64.tar.gz
  - K8S_FLAVOR=kind
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/google-cloud-sdk/"
services:
- docker
before_install:
  # Enable swap
  - sudo fallocate -l 4G /swapfile
  - sudo chmod 600 /swapfile
  - sudo mkswap /swapfile
  - sudo swapon /swapfile
  - sudo sysctl vm.swappiness=10
  # log to remote registry
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin strapdata.azurecr.io
  - echo "$NEXUS_PASSWORD" | docker login -u "$NEXUS_USERNAME" --password-stdin https://docker.repo.strapdata.com
  # Installing Kind
  - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-$(uname)-amd64
  - chmod +x ./kind
  - export PATH=$PATH:$PWD
  - kind version
  # Installing Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - export PATH=$PATH:$PWD/linux-amd64/
install:
- cd ${TRAVIS_BUILD_DIR}
- ./gradlew --version
# Create Kind cluster and a local registry
- helm init --client-only
- integ-test/setup_cluster.sh
- kind get clusters
- docker ps -a
script:
- ./gradlew dockerPush -PregistryUrl="localhost:5000/" -PregistryInsecure
- ./gradlew java:edctl:buildExec
- integ-test/install_elassandra_operator.sh
# wait CRD deployed
- sleep 10
- kubectl get crd
- integ-test/test-scaleup-park-unpark-reaper.sh
- integ-test/test-multiple-dc.sh
# - (cd docs; make clean html SPHINXOPTS="-W")
deploy:
#- provider: script
#  skip_cleanup: true
#  script:
#  - ./gradlew dockerPush -PregistryUsername=$DOCKER_USERNAME -PregistryPassword=$DOCKER_PASSWORD -PregistryUrl=$DOCKER_URL
#  - ./gradlew publish -PrepoUsername=$NEXUS_USERNAME -PrepoPassword="$NEXUS_PASSWORD"
#  on:
#    tags: false
#    all_branches: true
#    condition: $TRAVIS_BRANCH =~ ^develop-.*

- provider: script
  skip_cleanup: true
  script:
    - ./gradlew dockerPush -PregistryUsername=$DOCKER_USERNAME -PregistryPassword=$DOCKER_PASSWORD -PregistryUrl=$DOCKER_URL
    - ./gradlew java:edctl:buildExec -Djib.to.auth.username=$DOCKER_USERNAME -Djib.to.auth.password=$DOCKER_PASSWORD
    - ./gradlew java:edctl:exec -Djib.to.auth.username=$DOCKER_USERNAME -Djib.to.auth.password=$DOCKER_PASSWORD
    - ./gradlew java:model:publish -PrepoUsername=$NEXUS_USERNAME -PrepoPassword=$NEXUS_PASSWORD
  # push to GCR.IO done by the marketplace repository
  on:
    tags: true
    branch:
      - master
