apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: strapkop
build:
  artifacts:
  - image: localhost:5000/strapdata/elassandra-operator
    context: java/operator
    jib:
      project: java:operator
      type: gradle
deploy:
  helm:
    releases:
    - name: dev-elassandra-operator
      chartPath: helm/src/main/helm/elassandra-operator
      namespace: default
      recreatePods: true
      skipBuildDependencies: true
      remote: false
      wait: false
      version: "0.3.0"
      values:
        images: localhost:5000/strapdata/elassandra-operator
profiles:
  - name: dev
    activation:
      - env: MICRONAUT_ENV=dev
        kubeContext: kind-cluster1
        command: dev