apiVersion: stable.strapdata.com/v1
kind: ElassandraDataCenter
metadata:
  name: {{ template "elassandra.fullname" . }}
  labels:
    app: {{ template "elassandra.name" . }}
    chart: {{ template "elassandra.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  clusterName: {{ .Values.clusterName }}
  replicas: {{ .Values.replicaCount }}
  elassandraImage: "{{ .Values.image.elassandraRepository }}:{{ .Values.image.elassandraTag }}"
  sidecarImage: "{{ .Values.image.sidecarRepository }}:{{ .Values.image.sidecarTag }}"
  imagePullPolicy: {{ .Values.imagePullPolicy }}
  elasticsearchEnabled: {{ .Values.elasticsearchEnabled }}
  {{- if  .Values.imagePullSecret }}
  imagePullSecret: {{ .Values.imagePullSecret }}
  {{- else }}
  imagePullSecret: ""
  {{- end }}
  resources:
{{ toYaml .Values.resources | indent 4 }}
  dataVolumeClaim:
{{ toYaml .Values.dataVolumeClaim | indent 4 }}
{{- if .Values.env }}
  env:
{{ toYaml .Values.env | indent 4 }}
{{- end }}
{{- if .Values.restoreFromBackup }}
  restoreFromBackup: {{ .Values.restoreFromBackup }}
{{- end }}
{{- if .Values.userConfigMapVolumeSource }}
  userConfigMapVolumeSource:
{{ toYaml .Values.userConfigMapVolumeSource | indent 4 }}
{{- end }}
{{- if .Values.userSecretVolumeSource }}
  userSecretVolumeSource:
{{ toYaml .Values.userSecretVolumeSource | indent 4 }}
{{- end }}
  prometheusSupport: {{ .Values.prometheusEnabled }}
  privilegedSupported: {{ .Values.privilegedSupported }}
  hostPortEnabled: {{ default "true" .Values.hostPortEnabled }}
  nativePort : {{ default "39042" .Values.nativePort }}
  storagePort : {{ default "37000" .Values.storagePort }}
  sslStoragePort : {{ default "37001" .Values.sslStoragePort }}
{{- if .Values.ssl }}
  ssl:
{{ toYaml .Values.ssl | indent 4 }}
{{- end }}
{{- if .Values.authentication }}
  authentication:
{{ toYaml .Values.authentication | indent 4 }}
{{- end }}
{{- if .Values.enterprise }}
  enterprise:
{{ toYaml .Values.enterprise | indent 4 }}
{{- end }}