micronaut:
    application:
        name: elassandra-operator
    ssl:
        enabled: true
        port: 443
    server:
        ssl:
            #protocol: [ "SSLv3", "TLSv1", "TLSv1.1", "TLSv1.2" ]
            #ciphers: [ "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA", "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384" ]
            key-store:
                type: "${OPERATOR_KEYSTORE_TYPE:PKCS12}"
                path: "${OPERATOR_KEYSTORE_PATH:`file:/tls/operator.p12`}"
                password: "${OPERATOR_KEYSTORE_PASSWORD:changeit}"
    executors:
        authority:
            type: FIXED
            number-of-threads: 2
        reaper:
            type: FIXED
            number-of-threads: 2
        tasks:
            type: FIXED
            number-of-threads: 8
        status:
            type: WORK_STEALING

    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M
                descriptions: true
endpoints:
    all:
        port: 8081
    info:
        enabled: true
        sensitive: false
    env:
        enabled: true
        sensitive: false
    stop:
        enabled: true
        sensitive: false
    metrics:
        enabled: true
        sensitive: false
        binders:
            jvm:
                enabled: true
            web:
                enabled: true
            uptime:
                enabled: true
            processor:
                enabled: true
    prometheus:
        sensitive: false
jackson:
    module-scan: true
    serialization-inclusion: NON_NULL

operator:
    jmxmpPort: ${JMXMP_PORT:7199}
    k8sWatchPeriodInSec: ${K8S_WATCH_PERIOD:180}
    elassandraNodeWatchPeriodInSec: ${ELASSANDRA_NODE_WATCH_PERIOD:60}
    namespace: "${OPERATOR_NAMESPACE:}"
    serviceName: "${OPERATOR_SERVICE_NAME:elassandra-operator}"
    tasks:
        retentionPeriod: "${TASKS_RETENTION:7D}"