micronaut:
    server:
        port: 8080
    application:
        name: elassandra-operator
    executors:
        authority:
            type: FIXED
            number-of-threads: 2
        reaper:
            type: FIXED
            number-of-threads: 2
        tasks:
            type: FIXED
            number-of-threads: 8
        status:
            type: WORK_STEALING

    router:
        static-resources:
            swagger:
                enabled: true
                paths:
                    - classpath:META-INF/swagger
                    - classpath:swagger
                mapping: /swagger/**
    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M
                descriptions: true
endpoints:
    all:
        port: 8081
    info:
        enabled: true
        sensitive: false
    env:
        enabled: true
        sensitive: false
    stop:
        enabled: true
        sensitive: false
    metrics:
        enabled: true
        sensitive: false
        binders:
            jvm:
                enabled: true
            web:
                enabled: true
            uptime:
                enabled: true
            processor:
                enabled: true
    prometheus:
        sensitive: false
jackson:
    module-scan: false

operator:
    k8sWatchPeriodInSec: ${K8S_WATCH_PERIOD:180}
    elassandraNodeWatchPeriodInSec: ${ELASSANDRA_NODE_WATCH_PERIOD:60}
    namespace: "${OPERATOR_NAMESPACE:}"
    serviceName: "${OPERATOR_SERVICE_NAME:elassandra-operator}"
    test:
        enabled: "${TESTSUITE_ENABLE:false}"
        platform: "${TESTSUITE_PLATFORM:LOCAL}"
    tasks:
        retentionPeriod: "${TASKS_RETENTION:7D}"