#
# Copyright (C) 2020 Strapdata SAS (support@strapdata.com)
#
# The Elassandra-Operator is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The Elassandra-Operator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Elassandra-Operator.  If not, see <http://www.gnu.org/licenses/>.
#

micronaut:
    application:
        name: elassandra-operator
    ssl:
        enabled: ${OPERATOR_SSL:true}
        port: ${OPERATOR_SERVER_PORT:443}
    server:
        ssl:
            key-store:
                type: "${OPERATOR_KEYSTORE_TYPE:PKCS12}"
                path: "${OPERATOR_KEYSTORE_PATH:`file:/tls/operator.p12`}"
                password: "${OPERATOR_KEYSTORE_PASSWORD:changeit}"
#        netty:
#            log-level: TRACE
    executors:
        workqueue:
            type: CACHED
        taskqueue:
            type: CACHED
        authority:
            type: CACHED
        reaper:
            type: CACHED
        tasks:
            type: CACHED
    metrics:
        enabled: true
        export:
            prometheus:
                enabled: ${OPERATOR_PROMETHEUS_ENABLED:true}
                step: PT1M
                descriptions: true
endpoints:
    all:
        port: ${OPERATOR_ENDPOINTS_PORT:8081}
    info:
        enabled: true
        sensitive: false
    env:
        enabled: true
        sensitive: false
    stop:
        enabled: true
        sensitive: false
    caches:
        enabled: true
        sensitive: false
    loggers:
        enabled: true
        sensitive: false
    metrics:
        enabled: true
        sensitive: false
        binders:
            jvm:
                enabled: true
            web:
                enabled: true
            uptime:
                enabled: true
            processor:
                enabled: true
    prometheus:
        sensitive: false
jackson:
    module-scan: true
    serialization-inclusion: NON_NULL
operator:
    jmxmpPort: ${OPERATOR_JMXMP_PORT:7199}
    k8sWatchPeriodInSec: ${OPERATOR_K8S_WATCH_PERIOD:180}
    operatorNamespace: "${OPERATOR_NAMESPACE:default}"
    watchNamespace: "${OPERATOR_WATCH_NAMESPACE:}"
    serviceName: "${OPERATOR_SERVICE_NAME:elassandra-operator}"
    runSysctl: "${OPERATOR_RUN_SYSCTL:true}"
    tasks:
        retentionPeriod: "${OPERATOR_TASKS_RETENTION:7D}"