micronaut:
    application:
        name: operator
    router:
        static-resources:
            swagger:
                enabled: true
                paths:
                    - classpath:META-INF/swagger
                    - classpath:swagger
                mapping: /swagger/**
jackson:
    module-scan: false

operator:
    namespace: ${OPERATOR_NAMESPACE:default}