data_file_directories:
  - /var/lib/cassandra/data

commitlog_directory: /var/lib/cassandra/commitlog

saved_caches_directory: /var/lib/cassandra/saved_caches

hints_directory: /var/lib/cassandra/hints

cdc_raw_directory: /var/lib/cassandra/cdc