# Default values for elassandra-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

apiVersion: stable.strapdata.com/v1

image:
  repository: localhost:32000/strapdata/elassandra-operator-dev
  tag: latest

imagePullPolicy: Always
imagePullSecrets:

resources: {}

env:
  TESTSUITE_ENABLE: true
  LOGBACK_com_strapdata_strapkop_test: DEBUG

ingress:
  enabled: false

nodeSelector: {}

rbacEnable: true

tolerations: []

affinity: {}
