micronaut:
    dns:
        subscriptionId: ${AZURE_SUBSCRIPTION_ID}
        resourceGroup: ${AZURE_RESOURCE_GROUP}
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        domain: ${DNS_DOMAIN}
        ttl: ${DNS_TTL:60}
    ssl:
        enabled: ${SIDECAR_SSL_ENABLE:false}
        keyStore:
            path:  ${SIDECAR_SSL_KEYSTORE_PATH}
            password: ${SIDECAR_SSL_KEYSTORE_SECRET}
            type: PKCS12
    application:
        name: sidecar
    router:
        static-resources:
            swagger:
                enabled: true
                paths:
                    - classpath:META-INF/swagger
                    - classpath:swagger
                mapping: /swagger/**
sidecar:
    dnsDomain: "${DNS_DOMAIN}"
    dnsTtl: "${DNS_TTL:60}"
jackson:
    module-scan: false