apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: kube-system
  labels:
    k8s-app: kube-registry
spec:
  selector:
    kubernetes.io/minikube-addons: registry
  type: NodePort
  ports:
    - name: registry
      targetPort: 5000
      port: 30500
      protocol: TCP
      nodePort: 30500
      hostPort: 30500