# Default values for elassandra-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

apiVersion: stable.strapdata.com/v1

dns:
  azureSecretName:

image:
  repository: localhost:32000/strapdata/elassandra-operator-dev
  tag: latest

imagePullPolicy: Always
imagePullSecrets:

resources: {}
# Suggested resource limits for the operator itself (not elassandra), works with a reasonable sized minikube.
#  limits:
#    cpu: 200m
#    memory: 100Mi
#  requests:
#    cpu: 100m
#    memory: 50Mi

env:
#  NODEINFO_SECRET: "nodeinfo-token-zhfc7"
#  INGRESS_DOMAIN: "minikube.strapcloud.localnet"
#  K8S_API_DEBUG: true

ingress:
  enabled: false
  hosts:
    - strapkop.minikube.strapcloud.localnet
  annotations:
    kubernetes.io/ingress.class: traefik
#  tls:
#  - hosts:
#    - strapkop.941a7aa2-kube1-azure-northeurope.azure.strapcloud.com

nodeSelector: {}

rbacEnable: true

tolerations: []

affinity: {}

# env: []
