# Default values for elassandra-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

apiVersion: stable.strapdata.com/v1

image:
  repository:  docker.repo.strapdata.com/strapdata/elassandra-operator-dev
  tag: latest

imagePullPolicy: Always
imagePullSecret: "strapdata-cr"

resources: {}
# Suggested resource limits for the operator itself (not elassandra), works with a reasonable sized minikube.
#  limits:
#    cpu: 200m
#    memory: 100Mi
#  requests:
#    cpu: 100m
#    memory: 50Mi

env:
  NODEINFO_SECRET: "nodeinfo-token-zhfc7"
  DNS_DOMAIN: "minikube.strapcloud.localnet"

ingress:
  enabled: true
  hosts:
    - strapkop.minikube.strapcloud.localnet
  annotations:
    kubernetes.io/ingress.class: ngnix
#  tls:
#  - hosts:
#    - strapkop.941a7aa2-kube1-azure-northeurope.azure.strapcloud.com

nodeSelector: {}

rbacEnable: true

tolerations: []

affinity: {}

# env: []
