apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: elassandra-restores.stable.strapdata.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.strapdata.com
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: elassandra-restores
    # singular name to be used as an alias on the CLI and for display
    singular: elassandra-restore
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ElassandraRestore
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - cback
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
          - backupType
          properties:
            targetBackup:
              type: string
              description: The backup name to restore