---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "elassandra.resourceName" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elassandra.serviceAccount" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "elassandra.serviceAccount" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "elassandra.serviceAccount" . }}
    namespace: {{ .Release.Namespace }}