apiVersion: stable.strapdata.com/v1
kind: ElassandraDataCenter
metadata:
  name: {{ template "elassandra.resourceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "elassandra.name" . }}
    chart: {{ template "elassandra.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  clusterName: {{ include "elassandra.clusterName" . | required "Invalid clusterName : Release name has to be clustername-dcname (in lowercase), clustername must match ([0-9a-z]+)" }}
  datacenterName: {{ include "elassandra.datacenterName" . | required "Invalid datacenterName : Release name has to be clustername-dcname (in lowercase), datacenterName must match ([0-9a-z]+)" }}
  workload: {{ .Values.workload }}
  replicas: {{ .Values.replicas }}
{{- if .Values.replicasMode }}
  replicasMode: {{ .Values.replicasMode }}
{{- end }}
  elassandraImage: "{{ .Values.image.elassandraRepository }}:{{ .Values.image.elassandraTag }}"
  sidecarImage: "{{ .Values.image.sidecarRepository }}:{{ .Values.image.sidecarTag }}"
  imagePullPolicy: {{ .Values.imagePullPolicy }}
  elasticsearchEnabled: {{ .Values.elasticsearchEnabled }}
  imagePullSecret: {{ default "" .Values.imagePullSecret }}
  resources:
{{ toYaml .Values.resources | indent 4 }}
  dataVolumeClaim:
{{ toYaml .Values.dataVolumeClaim | indent 4 }}
{{- if .Values.env }}
  env:
{{ toYaml .Values.env | indent 4 }}
{{- end }}
{{- if .Values.restoreFromBackup }}
  restoreFromBackup:
{{ toYaml .Values.restoreFromBackup | indent 4 }}
{{- end }}
  userConfigMapVolumeSource:
    name: {{ template "elassandra.resourceName" . }}
    items:
{{- range $key, $val := .Values.configs }}
      - key: {{ $key }}
        path: {{ $key }}
{{- end }}
{{- if .Values.userConfigMapVolumeSource }}
{{ toYaml .Values.userConfigMapVolumeSource | indent 4 }}
{{- end }}
{{- if .Values.userSecretVolumeSource }}
  userSecretVolumeSource:
{{ toYaml .Values.userSecretVolumeSource | indent 4 }}
{{- end }}
  prometheusEnabled: {{ default "false" .Values.prometheusEnabled }}
  reaperEnabled: {{ default "false" .Values.reaperEnabled }}
{{- if .Values.reaper }}
  reaper:
{{- if .Values.reaper.image }}
    image:  {{ .Values.reaper.image }}
{{- end }}
{{- end }}

  privilegedSupported: {{ default "false" .Values.privilegedSupported }}
  hostPortEnabled: {{ default "false" .Values.hostPortEnabled }}
  hostNetworkEnabled: {{ default "false" .Values.hostNetworkEnabled }}
  nativePort : {{ default "9042" .Values.nativePort | quote }}
  storagePort : {{ default "7000" .Values.storagePort | quote }}
  sslStoragePort : {{ default "7001" .Values.sslStoragePort | quote }}
{{- if .Values.jdbPort }}
  jdbPort: {{ .Values.jdbPort }}
{{- end }}
{{- if .Values.jmxPort }}
  jmxPort: {{ .Values.jmxPort }}
{{- end }}
{{- if .Values.jmxmpEnabled }}
  jmxmpEnabled: {{ .Values.jmxmpEnabled }}
{{- end }}
{{- if .Values.jmxmpOverSSL }}
  jmxmpOverSSL: {{ .Values.jmxmpOverSSL }}
{{- end }}
{{- if .Values.ssl }}
  ssl:
{{ toYaml .Values.ssl | indent 4 }}
{{- end }}
{{- if .Values.authentication }}
  authentication:
{{ toYaml .Values.authentication | indent 4 }}
{{- end }}
{{- if .Values.enterprise }}
  enterprise:
{{ toYaml .Values.enterprise | indent 4 }}
{{- end }}
{{- if .Values.remoteSeeds }}
  remoteSeeds:
{{ toYaml .Values.remoteSeeds | indent 4 }}
{{- end }}
{{- if .Values.remoteSeeders }}
  remoteSeeders:
{{ toYaml .Values.remoteSeeders | indent 4 }}
{{- end }}
{{- if .Values.datacenterGroup }}
  datacenterGroup:
{{ toYaml .Values.datacenterGroup | indent 4 }}
{{- end }}
{{- if .Values.kibanaSpaces }}
  kibanaSpaces:
{{ toYaml .Values.kibanaSpaces | indent 4 }}
{{- end }}