---
# Create a service account API token bound to the nodeinfo serviceaccount
# Must to be created after serviceaccount, otherwise deleted by the token controller
# see https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nodeinfo
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: nodeinfo
    "helm.sh/hook": post-install
type: kubernetes.io/service-account-token