{{- if .Values.rbacEnabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "elassandra-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elassandra-operator.fullname" . }}
rules:
- apiGroups:
  - "authorization.k8s.io"
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - elassandra.strapdata.com
  resources:
  - elassandradatacenters
  - elassandradatacenters/status
  - elassandradatacenters/finalizers
  - elassandratasks
  - elassandratasks/status
  - elassandratasks/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs: ['*']
- apiGroups: ['']
  resources:
  - configmaps
  - secrets
  verbs: ['*']
- apiGroups: ['']
  resources:
  - pods
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups: ['']
  resources:
  - services
  - endpoints
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "extensions"
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - poddisruptionbudgets/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
- nonResourceURLs: ["/version", "/version/*"]
  verbs:
  - get
- apiGroups: ['']
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: ['']
  resources:
  - namespaces
  verbs:
  - list
{{- end }}
