apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "elassandra-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    operator: elassandra
    release: {{ .Release.Name }}
  name: {{ template "elassandra-operator.fullname" . }}
spec:
  replicas: {{ default "1" .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "elassandra-operator.name" . }}
      operator: elassandra
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "elassandra-operator.name" . }}
        operator: elassandra
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.image.pullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
      {{- end }}
      terminationGracePeriodSeconds: 45
      containers:
        - name: {{ template "elassandra-operator.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          terminationMessagePolicy: "FallbackToLogsOnError"
#          Uncomment and modify to change operator behaviour via start up flags
#          command: ["java"]
#          args: ["-jar", "/opt/lib/elassandra-operator/elassandra-operator.jar", "--no-version-check=false"]
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 5005
              name: jdb
            - containerPort: 7199
              name: jmx
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          lifecycle:
            preStop:
              httpGet:
                path: /shutdown/graceful
                port: 8080
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
          - name: ELASSANDRA_OPERATOR_NAME
            value: {{ template "elassandra-operator.fullname" . }}
          - name: OPERATOR_NAMESPACE
            value: {{ .Release.Namespace }}
          {{- if .Values.env }}
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.dns.domain }}
          - name: "DNS_DOMAIN"
            value: {{ .Values.dns.domain | quote }}
          {{- end }}
          - name: "DNS_TTL"
            value: {{ default "60" .Values.dns.ttl | quote }}
          {{- if .Values.dns.azure.secretName }}
          - name: "DNS_UPDATER_ENABLED"
            value: "true"
          - name: "DNS_AZURE_SECRET_NAME"
            value: {{ .Values.dns.azure.secretName | quote }}
          - name: "DNS_AZURE_CLIENT_ID"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.dns.azure.secretName | quote }}
                key: clientId
          - name: "DNS_AZURE_TENANT_ID"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.dns.azure.secretName | quote }}
                key: tenantId
          - name: "DNS_AZURE_CLIENT_SECRET"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.dns.azure.secretName | quote}}
                key: clientSecret
          - name: "DNS_AZURE_SUBSCRIPTION_ID"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.dns.azure.secretName | quote }}
                key: subscriptionId
          - name: "DNS_AZURE_RESOURCE_GROUP"
            valueFrom:
               secretKeyRef:
                 name: {{ .Values.dns.azure.secretName | quote }}
                 key: resourceGroup
         {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.rbacEnable }}
      serviceAccountName: {{ template "elassandra-operator.fullname" . }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}

