apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "elassandra-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elassandra-operator.fullname" . }}
spec:
  replicas: {{ default "1" .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "elassandra-operator.name" . }}
      operator: elassandra
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "elassandra-operator.name" . }}
        operator: elassandra
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: {{ default "true" .Values.prometheusEnabled | quote }}
        prometheus.io/port: {{ default "8081" .Values.managementPort | quote }}
        prometheus.io/path: "/prometheus"
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.image.pullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
      {{- end }}
      terminationGracePeriodSeconds: 45
      initContainers:
        # build a PKCS12 keystore from the TLS secret for the micronaut server
        - name: tlshook
          image: strapdata/tlshook:0.1
          imagePullPolicy: Always
          terminationMessagePolicy: "FallbackToLogsOnError"
          volumeMounts:
          - name: tls-secret-volume
            readOnly: true
            mountPath: "/tls-secret"
          - name: tls-volume
            mountPath: "/tls"
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      containers:
        - name: {{ template "elassandra-operator.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          terminationMessagePolicy: "FallbackToLogsOnError"
          volumeMounts:
            - name: tls-volume
              mountPath: "/tls"
          ports:
            - containerPort: {{ default 8443 .Values.serverPort }}
              name: https
            - containerPort: {{ default 8081 .Values.managementPort }}
              name: management
            {{- if .Values.jmxmpPort }}
            - containerPort: {{ .Values.jmxmpPort }}
              name: jmxmp
            {{- end }}
            - containerPort: 5005
              name: jdb
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /ready
              port: {{ default 8443 .Values.serverPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          lifecycle:
            preStop:
              httpGet:
                scheme: HTTPS
                path: /shutdown/graceful
                port: {{ default 8443 .Values.serverPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
          - name: OPERATOR_SERVICE_NAME
            value: {{ template "elassandra-operator.name" . }}
          {{- if .Values.serverPort }}
          - name: OPERATOR_SERVER_PORT
            value: {{ .Values.serverPort | quote }}
          {{- end }}
          {{- if .Values.managementPort }}
          - name: OPERATOR_MANAGEMENT_PORT
            value: {{ .Values.managementPort | quote }}
          {{- end }}
          {{- if .Values.jmxmpPort }}
          - name: OPERATOR_JMXMP_PORT
            value: {{ .Values.jmxmpPort | quote }}
          {{- end }}
          {{- if .Values.prometheusEnabled }}
          - name: OPERATOR_PROMETHEUS_ENABLED
            value: {{ .Values.prometheusEnabled | quote }}
          {{- end }}
          - name: OPERATOR_TASKS_RETENTION
            value: {{ default "7D" .Values.taskRetention | quote }}
          - name: ADDRESS_TRANSLATOR_DNS_DOMAIN
            value: {{ default "internal.strapdata.com" .Values.translatorDnsDomain | quote }}
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- if .Values.watchNamespace }}
          - name: OPERATOR_WATCH_NAMESPACE
            value: {{ .Values.watchNamespace }}
          {{- end }}
          {{- if .Values.env }}
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- end }}
      volumes:
      - name: tls-volume
        emptyDir: {}
      - name: tls-secret-volume
        secret:
          secretName: {{ template "elassandra-operator.name" . }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.rbacEnabled }}
      serviceAccountName: {{ template "elassandra-operator.fullname" . }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}

