{{- if .Values.ingress.enabled -}}
{{- $serviceAPIName := include "elassandra-operator.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ template "elassandra-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    operator: elassandra
    release: {{ .Release.Name }}
  name: {{ template "elassandra-operator.fullname" . }}-internal
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - path: /seeds
        backend:
          serviceName: {{ $serviceAPIName }}
          servicePort: http
{{- end -}}