# Elassandra-operator TLS certificate and key, populated by the operator init-container
apiVersion: v1
kind: Secret
metadata:
  name: elassandra-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "elassandra-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  tls.crt: Cg==
  tls.key: Cg==