apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "elassandra-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    operator: elassandra
    release: {{ .Release.Name }}
  name: {{ template "elassandra-operator.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: endpoints
  selector:
    app: {{ template "elassandra-operator.name" . }}
    release: {{ .Release.Name }}