apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "elassandra-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    operator: elassandra
    release: {{ .Release.Name }}
  name: {{ template "elassandra-operator.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ default 443 .Values.serverPort }}
      targetPort: {{ default 443 .Values.serverPort }}
      protocol: TCP
      name: https
    - port: {{ default 8081 .Values.managementPort }}
      targetPort: {{ default 8081 .Values.managementPort }}
      protocol: TCP
      name: endpoints
  selector:
    app: {{ template "elassandra-operator.name" . }}
    release: {{ .Release.Name }}