# Elassandra-operator TLS certificate and key
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "elassandra-operator.name" . }}
  labels:
    app: {{ template "elassandra-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: "kubernetes.io/tls"
data:
  tls.crt: {{ .Values.tls.crt | quote }}
  tls.key: {{ .Values.tls.key | quote }}