#
# Copyright (C) 2020 Strapdata SAS (support@strapdata.com)
#
# The Elassandra-Operator is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The Elassandra-Operator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Elassandra-Operator.  If not, see <http://www.gnu.org/licenses/>.
#

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: elassandradatacenters.elassandra.strapdata.com
  annotations:
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: elassandra.strapdata.com
  # version name to use for REST API: /apis/<group>/<version>
  version: v1beta1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: elassandradatacenters
    # singular name to be used as an alias on the CLI and for display
    singular: elassandradatacenter
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ElassandraDatacenter
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - edc
  subresources:
    # status enables the status subresource.
    status: {}
