#
# Copyright (C) 2020 Strapdata SAS (support@strapdata.com)
#
# The Elassandra-Operator is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The Elassandra-Operator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Elassandra-Operator.  If not, see <http://www.gnu.org/licenses/>.
#

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: elassandratasks.elassandra.strapdata.com
  annotations:
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: elassandra.strapdata.com
  # version name to use for REST API: /apis/<group>/<version>
  versions:
  - name: v1beta1
    storage: true
    served: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .status.phase
      name: phase
      type: string
    - jsonPath: .spec.cluster
      description: Elassandra cluster name
      name: cluster
      type: string
    - jsonPath: .spec.datacenter
      description: Elassandra datacenter name
      name: datacenter
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: age
      type: date
    schema:
      openAPIV3Schema:
        description: Elassandra task CRD
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              cluster:
                type: string
              datacenter:
                type: string
              cleanup:
                type: object
                properties:
                  keyspace:
                    type: string
                  waitIntervalInSec:
                    type: integer
                    format: int64
              repair:
                type: object
                properties:
                  srcDcName:
                    type: string
                  keyspace:
                    type: string
              rebuild:
                type: object
                properties:
                  srcDcName:
                    type: string
                  keyspace:
                    type: string
              updateRouting:
                type: object
                properties:
                  indices:
                    type: string
              removeNodes:
                type: object
                properties:
                  dcName:
                    type: string
              replication:
                type: object
                properties:
                  action:
                    type: string
                    enum:
                      - ADD
                      - REMOVE
                  dcName:
                    type: string
                  dcSize:
                    type: integer
                    format: int32
                  replicationMap:
                    type: object
                    additionalProperties:
                      type: integer
                      format: int32
              backup:
                type: object
                properties:
                  repository:
                    type: string
                  keyspaceRegex:
                    type: string
                  keyspaces:
                    type: array
                    items:
                      type: string
          status:
            type: object
            properties:
              observedGeneration:
                type: integer
                format: int64
              phase:
                type: string
                enum:
                  - WAITING
                  - RUNNING
                  - SUCCEED
                  - FAILED
                  - IGNORED
              startDate:
                type: string
                format: date-time
              durationInMs:
                type: integer
                format: int64
              lastMessage:
                type: string
              pods:
                type: object
                additionalProperties:
                  type: string
                  enum:
                    - WAITING
                    - RUNNING
                    - SUCCEED
                    - FAILED
                    - IGNORED
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    categories:
    - elassandra
    - cassandra
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: elassandratasks
    # singular name to be used as an alias on the CLI and for display
    singular: elassandratask
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ElassandraTask
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - et