# Default values for elassandra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
clusterName: Elassandra
replicaCount: 1

racks: 1
rackNodeSelectors: {}
#rackNodeSelectors:
#  rack1:
#    nodeSelectorTerms:
#      - matchExpressions:
#        - key: failure-domain.beta.kubernetes.io/zone
#          operator: In
#          values:
#            - europe-west1-b
#  rack2:
#    nodeSelectorTerms:
#      - matchExpressions:
#          - key: failure-domain.beta.kubernetes.io/zone
#            operator: In
#            values:
#              - europe-west1-c
#  rack3:
#    nodeSelectorTerms:
#      - matchExpressions:
#          - key: failure-domain.beta.kubernetes.io/zone
#            operator: In
#            values:
#              - europe-west1-d

image:
  elassandraRepository: strapdata/strapkop-elassandra-dev
  sidecarRepository: strapdata/strapkop-sidecar-dev
  elassandraTag: latest
  sidecarTag: latest

imagePullPolicy: Always
imagePullSecret: ""

privilegedSupported: true

resources:
  limits:
    memory: 1024Mi
  requests:
    memory: 1024Mi
dataVolumeClaim:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

enterprise:
  enabled: true
  jmx: true
  https: true
  ssl: true
  aaa:
    enabled: true
    audit: true
  cbs: true

#Example authentication for AWS S3 based backups
#env:
#  - name: AWS_ACCESS_KEY_ID
#    valueFrom:
#      secretKeyRef:
#        name: awsbackuptest
#        key: access
#  - name: AWS_SECRET_ACCESS_KEY
#    valueFrom:
#      secretKeyRef:
#        name: awsbackuptest
#        key: secret
#  - name: AWS_REGION
#    value: "us-west-2"

#Example authentication for AWS GCP based backups
#env:
#  - name: GOOGLE_APPLICATION_CREDENTIALS
#    value: "/tmp/user-config/service_key.json"
#  - name: GOOGLE_CLOUD_PROJECT
#    value: "elassandra-operator"
#  - name: BUCKET_NAME
#    value: "my-bucket"
#
#userConfigMapVolumeSource:
#  - name: configMapReference

## Example GCP ConfigMap
#apiVersion: extensions/v1beta1
#kind: ConfigMap
#metadata:
#  name: configMapReference
#data:
#  service_key.json: "XXXXXXXXX"



#restoreFromBackup: backup-hostname

prometheusEnabled: false
elasticsearchEnabled: true
ssl: true
authentication: CASSANDRA

hostPortEnabled: true

remoteSeeds: []