# Default values for elassandra-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

apiVersion: stable.strapdata.com/v1

image:
  repository: strapdata.azurecr.io/strapdata/elassandra-operator-dev
  tag: latest

imagePullPolicy: Always
imagePullSecrets: azurecr

resources: {}
# Suggested resource limits for the operator itself (not elassandra), works with a reasonable sized minikube.
#  limits:
#    cpu: 200m
#    memory: 100Mi
#  requests:
#    cpu: 100m
#    memory: 50Mi

env:
#  NODEINFO_SECRET: "nodeinfo-token-lqfhl"
#  INGRESS_DOMAIN: "941a7aa2-kube1-azure-northeurope.azure.strapcloud.com"
#  K8S_API_DEBUG: true

ingress:
  enabled: true
  hosts:
  - strapkop.941a7aa2-kube1-azure-northeurope.azure.strapcloud.com
  annotations:
    kubernetes.io/ingress.class: traefik
#  tls:
#  - hosts:
#    - strapkop.941a7aa2-kube1-azure-northeurope.azure.strapcloud.com

nodeSelector: {}

rbacEnable: true

tolerations: []

affinity: {}

# env: []
