# Default values for elassandra-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
apiVersion: stable.strapdata.com/v1

image:
  repository: strapdata.azurecr.io/strapdata/elassandra-operator-dev
  tag: 6.8.4.1
  pullPolicy: Always
  pullSecrets: []

replicas: 1

resources: {}
# Suggested resource limits for the operator itself (not elassandra), works with a reasonable sized minikube.
#  limits:
#    cpu: 200m
#    memory: 100Mi
#  requests:
#    cpu: 100m
#    memory: 50Mi

# Publish a CRD DNSEndpoint for external-dns on seed pods.
dns:
  enabled: true
  zone: ""
  ttl: 60

namespace:

env:
#  INGRESS_SUFFIX: "{datacenterName}-{clusterName}-{namespace}.int.test.strapkube.com"
#  K8S_API_DEBUG: true


ingress:
  enabled: false
  hosts: []
  annotations: {}
#    kubernetes.io/ingress.class: traefik
#  tls:
#  - hosts: []

#
elasticsearchLoadBalancerEnabled: false

nodeSelector: {}

rbacEnable: true

tolerations: []

affinity: {}

# env: []
