# Default values for elassandra-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: strapdata/elassandra-operator
  tag: latest
  pullPolicy: Always
  pullSecrets: []

replicas: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

# Elassandra-operator watched namespace
watchNamespace:

rbacEnabled: true

# Elassandra-operator config
#serverPort: 8443
#managementPort: 8081
#jmxmpPort: 7199
prometheusEnabled: true
taskRetention: "7D"

# k8s webhook validation settings
webhook:
  enabled: true
  failurePolicy: "Fail"
  timeoutSeconds: 15

# Additional env variables
env:

# Ingress for /seeds for cross-kubernetes connection
ingress:
  enabled: false
  hosts: []
  annotations: {}
#    kubernetes.io/ingress.class: traefik
#  tls:
#  - hosts: []

nodeSelector: {}

tolerations: []

affinity: {}
