# Default values for elassandra-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
apiVersion: stable.strapdata.com/v1

image:
  repository: strapdata.azurecr.io/strapdata/elassandra-operator-dev
  tag: 6.2.3.22
  pullPolicy: Always
  pullSecrets: []

replicas: 1

resources: {}
# Suggested resource limits for the operator itself (not elassandra), works with a reasonable sized minikube.
#  limits:
#    cpu: 200m
#    memory: 100Mi
#  requests:
#    cpu: 100m
#    memory: 50Mi

# DNS external updater for contact point
dns:
  enabled: true
  ttl: 60
  domainName: "azure.strapcloud.com"

namespace:

env:
#  DNS_DOMAIN
#  DNS_AZURE_CLIENT_ID:
#  DNS_AZURE_TENANT_ID:
#  DNS_AZURE_CLIENT_SECRET:
#  DNS_AZURE_SUBSCRIPTION_ID:
#  DNS_AZURE_RESOURCE_GROUP:
#  K8S_API_DEBUG: true

ingress:
  enabled: false
  hosts: []
  annotations: {}
#    kubernetes.io/ingress.class: traefik
#  tls:
#  - hosts: []

nodeSelector: {}

rbacEnable: true

tolerations: []

affinity: {}

# env: []
