{{- if .Values.rbacEnable }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "elassandra-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elassandra-operator.fullname" . }}
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - stable.strapdata.com
  resources:
  - elassandradatacenter
  - elassandradatacenters
  - elassandradatacenter/status
  - elassandradatacenters/status
  - elassandratask
  - elassandratasks
  - elassandratask/status
  - elassandratasks/status
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ['*']
- apiGroups: ['']
  resources:
  - configmaps
  - secrets
  verbs: ['*']
- apiGroups: ['']
  resources:
  - pods
  verbs: ['list', 'delete']
- apiGroups: ['']
  resources:
  - services
  - endpoints
  - persistentvolumeclaims
  - persistentvolumes
  verbs: ['get', 'create', 'update', 'delete', 'list']
- nonResourceURLs: ["/version", "/version/*"]
  verbs: ['get']
- apiGroups: ['']
  resources:
  - nodes
  verbs: ['list', 'watch']
- apiGroups: ['']
  resources:
  - namespaces
  verbs: ['list']
{{- end }}
