apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ template "storageclass.name" . }}
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
provisioner: {{ .Values.provisioner }}
parameters:
  type: {{ .Values.type }}
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowedTopologies:
  - matchLabelExpressions:
      - key: failure-domain.beta.kubernetes.io/zone
        values:
          - {{ .Values.zone }}